### ISSUE TITLE
Blend TextureFX doesn't work unless all textures are connencted

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#303]
reported by @michael-burk:

![image](https://user-images.githubusercontent.com/1094716/97016617-3ae9d480-154d-11eb-9533-42c7124edb40.png)

the mask should be optional.  it is another functionality to mask the texture. All I wanna do is blend :)
Also, the mask doesn't behave as expected at all.

**Comment by michael-burk** [comment]
The main point is, that the blend should work with just two connected textures.
The ones, that are supposed to be blended.
Everything else should be optional.

As a mask, I would also expect a kind of "multiply" behaviour. Maybe being able to choos luma, color channel, or else.
Also the "output texture" pin is not clear to me.

**Comment by azeno** [comment]
I just checked and the node works without having to connect the mask. Simply changing the opacity and it blends accordingly.

@michael-burk Most of the "Output Texture" pins now have a help text which explains what it's doing:
![image](https://user-images.githubusercontent.com/573618/101188011-6932f780-3655-11eb-9b3d-ef58c083314c.png)

The Blend node doesn't have that help text because it's a patched node. So I'd argue that's a different issue, would be nice if the system would forward the help text in such a case - something like if all connected pins have the same name and the same help use it.

Regarding the behavior of the mask please open a new issue.
