### ISSUE TITLE
TextureFX cleanup

### ISSUE THREAD

**Issue by tebjan** [vvvv/VL.Stride#314]
* [x] #482
* [x] research simplifying passes workflow see #481 
* [x] Don't use dynamic loops in blur shader code, use dynamic defines or different implementations
* [x] Control input? -> general mix/amount per texture with base shader?
* [x] enums for techniques
* [x] *Shader nodes should be experimental and advanced
* [x] research shader meta info
* [x] check VL wrapper nodes and connect to signature
* [x] RenderTargetFromInput ??
* [x] how to deal with double node names (shader + wrapper)
* [x] add help text for "Output Texture"
* [x] internal nodes

tebjan
* [x] EnumType attribute for input pins

elias
* [x] if not Texture0 oder Texture1 ... then leave name of the texture input and don't make it a filter
* [x] make Sampler appear after corresponding Texture input 
* [x] where is Sampler2? 
* [x] make sure default sampler is Linear, AddressUVW=wrap. and then remove node: AssignDefaultSampler

joreg
* [x] remove Tex2D(tex, uv)
* [x] remove all references to LinearSampler
* [x] Pixelate ambiguous

**Comment by azeno** [comment]
In my opinion shortcuts like `Tex2D` or `InTex` make the code harder to read because one immediately thinks it's something special/new and after digging it up you realize it's just the normal texture access but hiding facts like what sampler state is used for the access. So I'd vote for getting rid of it.

**Comment by tebjan** [comment]
The idea is to standardize getting the texture unless there is something special to do. and writing the full statement is just very long and users need to understand which texture and which sampler to use by default. so `InText()` takes this complexity away which is very good for non-shader pros. but I think that intermediate solutions like Tex2D add confusion and should be removed.

**Comment by bj-rn** [comment]
I thought InTex( ) is something stride introduced and searched their documentation, but nothing came up. If you implement these shortcuts they have to be really well documented otherwise it's just confusing. In my opinion you should stay with the standard way of doing things (HLSL or SSL?) which should also reduce your efforts since you can refer the users to microsoft or the stride documentation and they just can search for solutions on stackoverflow or whatever.

**Comment by tebjan** [comment]
> I thought InTex( ) is something stride introduced and searched their documentation, but nothing came up. If you implement these shortcuts they have to be really well documented otherwise it's just confusing.

this is defined in the main base shader. and if most texturefx nodes use that, it will be common knowledge.

> In my opinion you should stay with the standard way of doing things (HLSL or SSL?) which should also reduce your efforts since you can refer the users to microsoft or the stride documentation and they just can search for solutions on stackoverflow or whatever.

but we don't use the standard way, it is much harder to learn that you should use Texture0.SampleLevel(Sampler0, .., 0) instead of Sample and also it is way harder to type. InTex was developed after writing some texturefx and seeing all the repeated code, so it is a practical evolution everyone would come up with.

also, it is much easier to change the default behavior in the future if all nodes stick to this convention.

Tex2D was added later, also from a practical standpoint to shorten lines that use transformed uv coordinates, which is a special case and it could be argued that this can be removed since the sampling might be different if there is no 1:1 pixel correlation.

**Comment by tebjan** [comment]
moved all points to #444 or individual issues.
