### ISSUE TITLE
Expose Options Pins of the Texture2Ds inside RenderTexture

### ISSUE THREAD

**Issue by bj-rn** [vvvv/VL.Stride#338]
To be able to share Textures from Stride to beta/DX11.

![image](https://user-images.githubusercontent.com/1632591/99293103-14604600-283a-11eb-92f2-289870515df6.png)

![image](https://user-images.githubusercontent.com/1632591/99293130-1cb88100-283a-11eb-9264-6c6ce1b6bca6.png)

**Comment by tebjan** [comment]
there are now new optional pins on the `RenderTexture`, but it is not recommended to share a render target if rendering to the target takes a long time, because the render target is locked during rendering and the other application cannot access it and will be blocked.

so for these cases, there is now also `AsSharedTexture` which does a GPU resource copy which is very fast and should only lock the shared texture for a minimal amount of time.

![image](https://user-images.githubusercontent.com/1094716/99326072-d84bd600-2877-11eb-9713-0eb4add377fc.png)
