### ISSUE TITLE
SceneWindow doesn't keep position

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Stride#351]
https://discourse.vvvv.org/t/keeping-position-and-size-of-scenewindow/18964

**Comment by joreg** [comment]
same for new TextureWindow

**Comment by gregsn** [comment]
It looks like a solution management issue. E.g. move window, add node nearby and the position change suddenly is in the pin.

**Comment by azeno** [comment]
The used ids don't match because VL.Stride usually gets loaded from cache. Let's start from scratch what happens here:

Each process node stores its node path. The node path is constructed by appending the identity of the source code element representing that node. That identity is hard coded in the target code.
The `RenderWindow` uses its own node path to write to the first unconnected `Bounds` pin further up. So for example it will first try to write to it's own pin and if that is already connected it will traverse further out to the `SceneWindow` etc.

So the culprit is the hard coded identity of the `RenderWindow` node. If VL.Stride gets loaded from cache (which is usually the case), that identity won't match (or match a completely different node) and the attempt to write to the pin will fail.

So I guess we'll need to change the public API to use the persistent ids (strings). Any better ideas?

**Comment by tebjan** [comment]
was this tested? i currently experience that newly saved patches open with the window at (0, 0) position.

**Comment by tebjan** [comment]
That was a glitch. it doesn't seem to work when SceneWindow is changed/recompiled during a session. It works after a restart.

**Comment by azeno** [comment]
I believe this is because of the flag used in the renderer to commit the solution - it explicitly disables the compiler.

**Comment by tebjan** [comment]
There is another issue. it seems like a bounds change gets added to the undo history at the moment. that can be confusing because it feels like undo doesn't work anymore if a user moved the window a few times. there is no feedback that the undo then undoes all the window bounds changes.
