### ISSUE TITLE
Non-experimental Keyboard, Mouse, Touch nodes for Stride

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Stride#437]

**Comment by joreg** [comment]
also fix touch ids: #348

**Comment by joreg** [comment]
also make better helps for mouse, keyboard touch. the current "HowTo Get Mouse, Keyboard Touch of Window" makes no sense at all.

- show mouse, keyboard, touch in separate patches
- show those for both Scene- and RenderWindow?!
- mouse and touch need to visualize the positions in the window
- for keyboard also show keybang, -pressed and -toggle nodes

**Comment by joreg** [comment]
also answer here: https://discourse.vvvv.org/t/mouse-coordinates-in-stride/19324

**Comment by joreg** [comment]
further issues reported:

https://discourse.vvvv.org/t/mouse-coordinates-in-stride/19324

ravel: Hi there. Something weird is just happening with the mouse Position in the Stride Renderer. If I change the renderer size the MousePosition stays the same proportional according to my screen and not to the renderer window. So the Mouse Pos in the renderer goes from 0 to 0.5 if I change the renderer to half size. F8 and F5 is fixing it again.  

bjorn: When going fullscreen on a secondary monitor, the Mouse position in Stride no longer  goes from 0 to 1. In windowed mode it does. Is this a bug? 

tebjan: I've seen that before, someone reported it a while ago. It seems that the mouse coordinate scaling isn't updated on every window change. We'll investigate...

bentec: in his game, when resizing the window or going fullscreen, the mouse-ray is off

**Comment by joreg** [comment]
- [ ] Touch and Mouse nodes return Position only in normalized 0..1 with Y positive down. For 2d drawing we'd need a Worldspace Position with positive Y up? NOTE: skia and stride Y are not compatible. think: using a skiarenderer in stride...
- [ ] make PointerPoint non-advanced, since it is essential when working with Touch
- [ ] Touch, Mouse and Keyboard nodes return a Spread of InputEvent: shouldn't that rather be an Observable of InputEvent?
- [ ] Touch, Mouse and Keyboard nodes return a Device. What can it be used for? Can it be optional?
- [ ] We also need a simple Camera (2d) as we have in skia
- [ ] Make Mouse/Keyboard/Touch nodes also work with RenderWindow
- [ ] Make Mouse/Keyboard/Touch nodes also work with TextureWindow
- [ ] Can we move IO.Mouse/Keyboard to VL.Skia, so in the nodebrowser those don't interfere when using only Stride?

**Comment by joreg** [comment]
Touch and Mouse nodes return Position only in normalized 0..1 with Y positive down. For 2d drawing we'd need a Worldspace Position with positive Y up? NOTE: skia and stride Y are not compatible. think: using a skiarenderer in stride...
[HowTo work with mouse coordinates.zip](https://github.com/vvvv/VL.Stride/files/7954293/HowTo.work.with.mouse.coordinates.zip)

**Comment by gregsn** [comment]
added a "Position In Projection" to the Mouse node. Didn't do it for touch yet. Let's finish position handling on the mouse first.

Regarding "Position In World" (as also seen in the Skia part of the patch
[HowTo work with mouse coordinates.zip](https://github.com/vvvv/VL.Stride/files/7964226/HowTo.work.with.mouse.coordinates.zip)
). It is quite nice and works well in Skia. The question is if it makes sense in the Stride world as well.
I am assuming that we can only do return a 2D Vector "Position In World" when
* we don't have a perspective lens
* the orthographic camera is not rotated
![grafik](https://user-images.githubusercontent.com/575557/151671361-808ac32c-a2b4-419a-95c9-a20274600a9c.png)

So the big question is whether it is didactic to add pins that only make sense in very limited set of scenarios and in most others return just weird values. Maybe we should tell people more about mouse rays and make them easy to work with.

**Comment by gregsn** [comment]
Ok. I found a way to output a "Position in World". Stride commit: f8aabfb5595275c34e6dc8451b8db40a92642812
[HowTo work with mouse coordinates.zip](https://github.com/vvvv/VL.Stride/files/7965048/HowTo.work.with.mouse.coordinates.zip)

**Comment by joreg** [comment]
"should the mouse node complain (orange node) when no Camera is attached?"
but for basic stuff it works also without camera, right? so no warning.

"should it be "Position in 2D World"
the datatype of Vector2 gives that away already, so no need for this.

Considerations:
- make optional: Position in Projection, Position, Delta, Surface Size, Surface Aspect Ratio, Events, Mouse Device
- remove experimental MouseRay node
- add info on Mouse Ray output: Requires a Camera to be connected to the Mouse node

**Comment by gregsn** [comment]
MouseRay node is quite nice for debugging (it has a helper)

**Comment by bj-rn** [comment]
Hey, are the following issues are also part of this overhaul?

* https://github.com/vvvv/VL.Stride/issues/89
* https://github.com/vvvv/VL.Stride/issues/114
* https://github.com/vvvv/VL.Stride/issues/147
* https://github.com/vvvv/VL.Stride/issues/292
* https://github.com/vvvv/VL.Stride/issues/125

Had to do all kinds of hackery to make Elementa "work" with SkiaRenderer during my latest project (using for example InputSimulator) and I assume these issues are related.

There is also this reported by catweasel in the chat once:
"Touch events in SKia, nice and snappy, touch events in stride, delayed and time stretched like a buffer filling faster than it can output. Is this related to the orbit cam that also does the same, or is this just me?"

I made the same observation. Will try to make a demo video while I still have a touchscreen.

**Comment by joreg** [comment]
"Hey, are the following issues also part of this overhaul?" unfortunately not. this issue is foremost concerned with getting the nodes useful and their naming/categorization right and thus out of experimental. the other issues go deeper and remain separate. 

"Touch events in SKia, nice and snappy, touch events in stride, delayed and time stretched like a buffer filling faster than it can output. Is this related to the orbit cam that also does the same, or is this just me?"
this would best be in a separate issue with demo.

**Comment by bj-rn** [comment]
> getting the nodes useful

Well tbh I think they will only be if they work for one of the most common usescases: bulding userinterfaces for touchscreens.
In the last 3 projects I have been working on I needed one. And every time it was very time consuming and I had to jump through all kinds of hoops to get there.

**Comment by bj-rn** [comment]
> this would best be in a separate issue with demo.

Unfortunately I cannot reproduce the behaviour with a simpler patch. May it is caused with the workarounds I had to add to Elementa to make it work with SkiaRenderer.

**Comment by azeno** [comment]
@bj-rn Three out of the five issues have just been addressed. Events not being snappy could've also been addressed by ae36b346cf552ff57cd1c0fb0edc909e93fad9a0 because the SDL event queue now gets tackled right in the moment of a message being posted and not later when the application becomes idle again. But couldn't check because no proper test patch at hand, in theory it would make sense that it's fixed as well.

**Comment by bj-rn** [comment]
Unfortunately I haven't got the touchscreen anymore so I also can't check the "snappiness".

**Comment by gregsn** [comment]
In retrospect, I think it made sense that we tackled some of the points in this issue and embraced short-term solutions that already enhanced the usability of the current design and distinguished them from the "perfect" long-term solutions #89. However, here are some leftovers that I would classify as to be tackled when doing that long-term solution:

- [ ] Make Mouse/Keyboard/Touch nodes also work with RenderWindow
- [ ] Make Mouse/Keyboard/Touch nodes also work with TextureWindow

There are several issues that prevent us from just rolling them out. In this case, it looks like implementing those nodes above will just make our long-term / "correct" approach of dealing with input devices harder as it leads us into a wrong direction and also adds hack onto hack, complexity onto complexity. Without going into too much detail here are some clues why I would argue this way:
* TextureWindow comes with a Texture Input. This is not a type that we can modify. We could do some trickery like using a `ConditionalWeakTable` in order to glue the IInputSource to texture. Thus be able to propagate those input devices upstream - in theory. However:
  * How do we grab the input device from downstream? Is there an idea already? How do we make this work when there is a chain of TextureFX connected to each other and the last texture goes into the TextureWindow? We need to fetch the input devices from this Texture. So maybe we need a `Group (Texture)` node that allows us to connect the `Mouse` node, which feeds the input device further upstream? Do we really want to introduce more and more nodes that go in a direction that is quite different from the long-term solution?
  * Mouse/Keyboard/Touch for RenderWindow and TextureWindow would lead to at least 7 more nodes and a hell of patches that look quite different, but all need to be taken care of. How does it feel to have all of these device nodes that differ in an Output pin? Do we want to have all of them in the node browser?
  * Or do we want to have Mouse/Keyboard/Touch with a generic output and make the nodes adapt when connected to Entity/IRenderer or Texture? This is very hard to implement, I already had a look at making them adaptive and also makes them even harder to use, because the output doesn't tell you where you can connect it to.
  
- [ ] We also need a simple Camera (2d) as we have in skia
Had a look at this. We again would have to duplicate patches: `FlatCameraControls` & `Camera (Flat)` of the VL.EditingFramework.
Both use MouseDevice, KeyboardDevice, but the ones from Stride.

- [ ] Touch: Missing Position in World output: Not sure. Do we maybe want to have them per PointerPoint? Do we want to also output a Ray? If PointerPoint (Split) would output this information, the user could fetch the info for spreads of pressed, down, and released pointers. I have no touch, so I unassign for now.

**Comment by gregsn** [comment]
we should pick up our discussion in #89. I added another sketch. Would like to close this

**Comment by joreg** [comment]
continues in #541
